name = "misub"
main = "functions/[[path]].js"
compatibility_date = "2024-06-13"

# KV 命名空间绑定
# 这是 wrangler.toml 在Pages项目中最重要的作用
[[kv_namespaces]]
binding = "MISUB_KV"
id = "ad806839ab434ebba6432a4d84f1d7a0" # 请确保这里是你正确的 KV ID
preview_id = "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>" # 请确保这里是你正确的预览 KV ID

# D1 数据库绑定
# 用于替代 KV 存储，解决写入限制问题
[[d1_databases]]
binding = "MISUB_DB"
database_name = "misub"
database_id = "7483b32a-3628-44db-a068-99e46eaf6bce" # 请替换为您的 D1 数据库 ID
preview_database_id = "7483b32a-3628-44db-a068-99e46eaf6bce" # 请替换为您的预览 D1 数据库 ID

# 你也可以在这里定义环境变量，但更推荐在Cloudflare控制面板设置
[vars]
ADMIN_PASSWORD = "admin"
COOKIE_SECRET = "a_very_long_random_secret_string"

[triggers]
# "*/30" 表示每30分鐘
# "0 */6 * * *" 表示每6小時
# 根據您的需要調整 cron 表達式
crons = ["0 */6 * * *"] 
